<?php

namespace Proxies\__CG__\Oro\Bundle\ShippingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ShippingMethodsConfigsRuleDestination extends \Oro\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRuleDestination implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'postalCodes', 'region', 'regionText', 'country', 'methodConfigsRule'];
        }

        return ['__isInitialized__', 'id', 'postalCodes', 'region', 'regionText', 'country', 'methodConfigsRule'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ShippingMethodsConfigsRuleDestination $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion($region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', [$region]);

        return parent::setRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', []);

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegionName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegionName', []);

        return parent::getRegionName();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegionCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegionCode', []);

        return parent::getRegionCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegionText($regionText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegionText', [$regionText]);

        return parent::setRegionText($regionText);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegionText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegionText', []);

        return parent::getRegionText();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryName', []);

        return parent::getCountryName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryIso3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryIso3', []);

        return parent::getCountryIso3();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryIso2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryIso2', []);

        return parent::getCountryIso2();
    }

    /**
     * {@inheritDoc}
     */
    public function setMethodConfigsRule(\Oro\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRule $methodConfigsRule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMethodConfigsRule', [$methodConfigsRule]);

        return parent::setMethodConfigsRule($methodConfigsRule);
    }

    /**
     * {@inheritDoc}
     */
    public function getMethodConfigsRule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMethodConfigsRule', []);

        return parent::getMethodConfigsRule();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCodes', []);

        return parent::getPostalCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function hasPostalCode(\Oro\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRuleDestinationPostalCode $postalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasPostalCode', [$postalCode]);

        return parent::hasPostalCode($postalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function addPostalCode(\Oro\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRuleDestinationPostalCode $postalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPostalCode', [$postalCode]);

        return parent::addPostalCode($postalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function removePostalCode(\Oro\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRuleDestinationPostalCode $postalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePostalCode', [$postalCode]);

        return parent::removePostalCode($postalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
