<?php

namespace Proxies\__CG__\Oro\Bundle\PaymentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PaymentMethodsConfigsRule extends \Oro\Bundle\PaymentBundle\Entity\PaymentMethodsConfigsRule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'methodConfigs', 'rule', 'destinations', 'currency', 'organization', 'websites', 'serialized_data'];
        }

        return ['__isInitialized__', 'id', 'methodConfigs', 'rule', 'destinations', 'currency', 'organization', 'websites', 'serialized_data'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PaymentMethodsConfigsRule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRule', []);

        return parent::getRule();
    }

    /**
     * {@inheritDoc}
     */
    public function setRule(\Oro\Bundle\RuleBundle\Entity\RuleInterface $rule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRule', [$rule]);

        return parent::setRule($rule);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMethodConfigs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMethodConfigs', []);

        return parent::getMethodConfigs();
    }

    /**
     * {@inheritDoc}
     */
    public function hasMethodConfig(\Oro\Bundle\PaymentBundle\Entity\PaymentMethodConfig $methodConfig)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasMethodConfig', [$methodConfig]);

        return parent::hasMethodConfig($methodConfig);
    }

    /**
     * {@inheritDoc}
     */
    public function addMethodConfig(\Oro\Bundle\PaymentBundle\Entity\PaymentMethodConfig $methodConfig)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMethodConfig', [$methodConfig]);

        return parent::addMethodConfig($methodConfig);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMethodConfig(\Oro\Bundle\PaymentBundle\Entity\PaymentMethodConfig $methodConfig)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMethodConfig', [$methodConfig]);

        return parent::removeMethodConfig($methodConfig);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinations', []);

        return parent::getDestinations();
    }

    /**
     * {@inheritDoc}
     */
    public function addDestination(\Oro\Bundle\PaymentBundle\Entity\PaymentMethodsConfigsRuleDestination $destination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDestination', [$destination]);

        return parent::addDestination($destination);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDestination(\Oro\Bundle\PaymentBundle\Entity\PaymentMethodsConfigsRuleDestination $destination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDestination', [$destination]);

        return parent::removeDestination($destination);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', []);

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\Oro\Bundle\OrganizationBundle\Entity\OrganizationInterface $organization)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', [$organization]);

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function addWebsite(\Oro\Bundle\WebsiteBundle\Entity\Website $website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWebsite', [$website]);

        return parent::addWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWebsite(\Oro\Bundle\WebsiteBundle\Entity\Website $website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWebsite', [$website]);

        return parent::removeWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsites()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsites', []);

        return parent::getWebsites();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerializedData($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerializedData', [$value]);

        return parent::setSerializedData($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerializedData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerializedData', []);

        return parent::getSerializedData();
    }

}
