<?php

namespace Proxies\__CG__\Oro\Bundle\SaleBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Quote extends \Oro\Bundle\SaleBundle\Entity\Quote implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'qid', 'website', 'request', 'poNumber', 'shipUntil', 'validUntil', 'quoteProducts', 'expired', 'pricesChanged', 'shippingAddress', 'assignedUsers', 'assignedCustomerUsers', 'shippingMethod', 'shippingMethodType', 'shippingMethodLocked', 'allowUnlistedShippingMethod', 'estimatedShippingCostAmount', 'overriddenShippingCostAmount', 'currency', 'demands', 'serialized_data', 'payment_term_7c4f1e8e', 'opportunity', 'internal_status', 'customer_status', 'ac_last_contact_date_out', 'ac_last_contact_date_in', 'ac_last_contact_date', 'ac_contact_count_out', 'ac_contact_count_in', 'ac_contact_count', 'owner', 'organization', 'customerUser', 'customer', 'createdAt', 'updatedAt', 'updatedAtSet'];
        }

        return ['__isInitialized__', 'id', 'qid', 'website', 'request', 'poNumber', 'shipUntil', 'validUntil', 'quoteProducts', 'expired', 'pricesChanged', 'shippingAddress', 'assignedUsers', 'assignedCustomerUsers', 'shippingMethod', 'shippingMethodType', 'shippingMethodLocked', 'allowUnlistedShippingMethod', 'estimatedShippingCostAmount', 'overriddenShippingCostAmount', 'currency', 'demands', 'serialized_data', 'payment_term_7c4f1e8e', 'opportunity', 'internal_status', 'customer_status', 'ac_last_contact_date_out', 'ac_last_contact_date_in', 'ac_last_contact_date', 'ac_contact_count_out', 'ac_contact_count_in', 'ac_contact_count', 'owner', 'organization', 'customerUser', 'customer', 'createdAt', 'updatedAt', 'updatedAtSet'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Quote $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', []);

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setQid($qid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQid', [$qid]);

        return parent::setQid($qid);
    }

    /**
     * {@inheritDoc}
     */
    public function getQid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQid', []);

        return parent::getQid();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidUntil(\DateTime $validUntil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidUntil', [$validUntil]);

        return parent::setValidUntil($validUntil);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidUntil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidUntil', []);

        return parent::getValidUntil();
    }

    /**
     * {@inheritDoc}
     */
    public function addQuoteProduct(\Oro\Bundle\SaleBundle\Entity\QuoteProduct $quoteProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQuoteProduct', [$quoteProduct]);

        return parent::addQuoteProduct($quoteProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeQuoteProduct(\Oro\Bundle\SaleBundle\Entity\QuoteProduct $quoteProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeQuoteProduct', [$quoteProduct]);

        return parent::removeQuoteProduct($quoteProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuoteProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuoteProducts', []);

        return parent::getQuoteProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequest(\Oro\Bundle\RFPBundle\Entity\Request $request = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequest', [$request]);

        return parent::setRequest($request);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequest', []);

        return parent::getRequest();
    }

    /**
     * {@inheritDoc}
     */
    public function isExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExpired', []);

        return parent::isExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired($expired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', [$expired]);

        return parent::setExpired($expired);
    }

    /**
     * {@inheritDoc}
     */
    public function isPricesChanged(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPricesChanged', []);

        return parent::isPricesChanged();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricesChanged(bool $pricesChanged): \Oro\Bundle\SaleBundle\Entity\Quote
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricesChanged', [$pricesChanged]);

        return parent::setPricesChanged($pricesChanged);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function hasOfferVariants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasOfferVariants', []);

        return parent::hasOfferVariants();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoNumber($poNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoNumber', [$poNumber]);

        return parent::setPoNumber($poNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoNumber', []);

        return parent::getPoNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setShipUntil(\DateTime $shipUntil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShipUntil', [$shipUntil]);

        return parent::setShipUntil($shipUntil);
    }

    /**
     * {@inheritDoc}
     */
    public function getShipUntil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShipUntil', []);

        return parent::getShipUntil();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', []);

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite(\Oro\Bundle\WebsiteBundle\Entity\Website $website = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', [$website]);

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress', []);

        return parent::getShippingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddress(\Oro\Bundle\SaleBundle\Entity\QuoteAddress $shippingAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddress', [$shippingAddress]);

        return parent::setShippingAddress($shippingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignedUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignedUsers', []);

        return parent::getAssignedUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addAssignedUser(\Oro\Bundle\UserBundle\Entity\User $assignedUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAssignedUser', [$assignedUser]);

        return parent::addAssignedUser($assignedUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAssignedUser(\Oro\Bundle\UserBundle\Entity\User $assignedUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAssignedUser', [$assignedUser]);

        return parent::removeAssignedUser($assignedUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignedCustomerUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignedCustomerUsers', []);

        return parent::getAssignedCustomerUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addAssignedCustomerUser(\Oro\Bundle\CustomerBundle\Entity\CustomerUser $assignedCustomerUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAssignedCustomerUser', [$assignedCustomerUser]);

        return parent::addAssignedCustomerUser($assignedCustomerUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAssignedCustomerUser(\Oro\Bundle\CustomerBundle\Entity\CustomerUser $assignedCustomerUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAssignedCustomerUser', [$assignedCustomerUser]);

        return parent::removeAssignedCustomerUser($assignedCustomerUser);
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethod', []);

        return parent::getShippingMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMethod($shippingMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMethod', [$shippingMethod]);

        return parent::setShippingMethod($shippingMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethodType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethodType', []);

        return parent::getShippingMethodType();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMethodType($shippingMethodType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMethodType', [$shippingMethodType]);

        return parent::setShippingMethodType($shippingMethodType);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingCost', []);

        return parent::getShippingCost();
    }

    /**
     * {@inheritDoc}
     */
    public function getEstimatedShippingCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstimatedShippingCost', []);

        return parent::getEstimatedShippingCost();
    }

    /**
     * {@inheritDoc}
     */
    public function getEstimatedShippingCostAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstimatedShippingCostAmount', []);

        return parent::getEstimatedShippingCostAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstimatedShippingCostAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstimatedShippingCostAmount', [$amount]);

        return parent::setEstimatedShippingCostAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getOverriddenShippingCostAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverriddenShippingCostAmount', []);

        return parent::getOverriddenShippingCostAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setOverriddenShippingCostAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOverriddenShippingCostAmount', [$amount]);

        return parent::setOverriddenShippingCostAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function isAcceptable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAcceptable', []);

        return parent::isAcceptable();
    }

    /**
     * {@inheritDoc}
     */
    public function getDemands()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemands', []);

        return parent::getDemands();
    }

    /**
     * {@inheritDoc}
     */
    public function isAllowUnlistedShippingMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAllowUnlistedShippingMethod', []);

        return parent::isAllowUnlistedShippingMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowUnlistedShippingMethod($allowUnlistedShippingMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowUnlistedShippingMethod', [$allowUnlistedShippingMethod]);

        return parent::setAllowUnlistedShippingMethod($allowUnlistedShippingMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function isShippingMethodLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isShippingMethodLocked', []);

        return parent::isShippingMethodLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMethodLocked($shippingMethodLocked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMethodLocked', [$shippingMethodLocked]);

        return parent::setShippingMethodLocked($shippingMethodLocked);
    }

    /**
     * {@inheritDoc}
     */
    public function isOverriddenShippingCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOverriddenShippingCost', []);

        return parent::isOverriddenShippingCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerializedData($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerializedData', [$value]);

        return parent::setSerializedData($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentTerm7c4f1e8e($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentTerm7c4f1e8e', [$value]);

        return parent::setPaymentTerm7c4f1e8e($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setOpportunity($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpportunity', [$value]);

        return parent::setOpportunity($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setInternalStatus($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInternalStatus', [$value]);

        return parent::setInternalStatus($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerStatus($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerStatus', [$value]);

        return parent::setCustomerStatus($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcLastContactDateOut($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcLastContactDateOut', [$value]);

        return parent::setAcLastContactDateOut($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcLastContactDateIn($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcLastContactDateIn', [$value]);

        return parent::setAcLastContactDateIn($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcLastContactDate($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcLastContactDate', [$value]);

        return parent::setAcLastContactDate($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcContactCountOut($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcContactCountOut', [$value]);

        return parent::setAcContactCountOut($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcContactCountIn($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcContactCountIn', [$value]);

        return parent::setAcContactCountIn($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setAcContactCount($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcContactCount', [$value]);

        return parent::setAcContactCount($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerializedData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerializedData', []);

        return parent::getSerializedData();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentTerm7c4f1e8e()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentTerm7c4f1e8e', []);

        return parent::getPaymentTerm7c4f1e8e();
    }

    /**
     * {@inheritDoc}
     */
    public function getOpportunity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpportunity', []);

        return parent::getOpportunity();
    }

    /**
     * {@inheritDoc}
     */
    public function getInternalStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInternalStatus', []);

        return parent::getInternalStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerStatus', []);

        return parent::getCustomerStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcLastContactDateOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcLastContactDateOut', []);

        return parent::getAcLastContactDateOut();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcLastContactDateIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcLastContactDateIn', []);

        return parent::getAcLastContactDateIn();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcLastContactDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcLastContactDate', []);

        return parent::getAcLastContactDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcContactCountOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcContactCountOut', []);

        return parent::getAcContactCountOut();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcContactCountIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcContactCountIn', []);

        return parent::getAcContactCountIn();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcContactCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcContactCount', []);

        return parent::getAcContactCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(\Oro\Bundle\UserBundle\Entity\User $owner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', []);

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization(\Oro\Bundle\OrganizationBundle\Entity\OrganizationInterface $organization)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', [$organization]);

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerUser', []);

        return parent::getCustomerUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerUser(\Oro\Bundle\CustomerBundle\Entity\CustomerUser $customerUser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerUser', [$customerUser]);

        return parent::setCustomerUser($customerUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', []);

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\Oro\Bundle\CustomerBundle\Entity\Customer $customer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', [$customer]);

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function isUpdatedAtSet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUpdatedAtSet', []);

        return parent::isUpdatedAtSet();
    }

}
