<?php

namespace Proxies\__CG__\Oro\Bundle\DotmailerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AddressBookContact extends \Oro\Bundle\DotmailerBundle\Entity\AddressBookContact implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'addressBook', 'contact', 'unsubscribedDate', 'marketingListItemId', 'marketingListItemClass', 'scheduledForExport', 'scheduledForFieldsUpdate', 'newEntity', 'entityUpdated', 'channel', 'exportId', 'status', 'serialized_data', 'exportOperationType'];
        }

        return ['__isInitialized__', 'id', 'addressBook', 'contact', 'unsubscribedDate', 'marketingListItemId', 'marketingListItemClass', 'scheduledForExport', 'scheduledForFieldsUpdate', 'newEntity', 'entityUpdated', 'channel', 'exportId', 'status', 'serialized_data', 'exportOperationType'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AddressBookContact $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressBook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressBook', []);

        return parent::getAddressBook();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressBook(\Oro\Bundle\DotmailerBundle\Entity\AddressBook $addressBook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressBook', [$addressBook]);

        return parent::setAddressBook($addressBook);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', []);

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact(\Oro\Bundle\DotmailerBundle\Entity\Contact $contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', [$contact]);

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnsubscribedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnsubscribedDate', []);

        return parent::getUnsubscribedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnsubscribedDate(\DateTime $unsubscribedDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnsubscribedDate', [$unsubscribedDate]);

        return parent::setUnsubscribedDate($unsubscribedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarketingListItemId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarketingListItemId', []);

        return parent::getMarketingListItemId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarketingListItemId($marketingListItemId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarketingListItemId', [$marketingListItemId]);

        return parent::setMarketingListItemId($marketingListItemId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarketingListItemClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarketingListItemClass', []);

        return parent::getMarketingListItemClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarketingListItemClass($marketingListItemClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarketingListItemClass', [$marketingListItemClass]);

        return parent::setMarketingListItemClass($marketingListItemClass);
    }

    /**
     * {@inheritDoc}
     */
    public function isScheduledForExport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isScheduledForExport', []);

        return parent::isScheduledForExport();
    }

    /**
     * {@inheritDoc}
     */
    public function setScheduledForExport($scheduledForExport)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScheduledForExport', [$scheduledForExport]);

        return parent::setScheduledForExport($scheduledForExport);
    }

    /**
     * {@inheritDoc}
     */
    public function isScheduledForFieldsUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isScheduledForFieldsUpdate', []);

        return parent::isScheduledForFieldsUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setScheduledForFieldsUpdate($scheduledForFieldsUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScheduledForFieldsUpdate', [$scheduledForFieldsUpdate]);

        return parent::setScheduledForFieldsUpdate($scheduledForFieldsUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function isNewEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNewEntity', []);

        return parent::isNewEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewEntity($newEntity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewEntity', [$newEntity]);

        return parent::setNewEntity($newEntity);
    }

    /**
     * {@inheritDoc}
     */
    public function isEntityUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEntityUpdated', []);

        return parent::isEntityUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntityUpdated($entityUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntityUpdated', [$entityUpdated]);

        return parent::setEntityUpdated($entityUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getChannel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannel', []);

        return parent::getChannel();
    }

    /**
     * {@inheritDoc}
     */
    public function setChannel(\Oro\Bundle\IntegrationBundle\Entity\Channel $channel = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChannel', [$channel]);

        return parent::setChannel($channel);
    }

    /**
     * {@inheritDoc}
     */
    public function getExportId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExportId', []);

        return parent::getExportId();
    }

    /**
     * {@inheritDoc}
     */
    public function setExportId($exportId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExportId', [$exportId]);

        return parent::setExportId($exportId);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$value]);

        return parent::setStatus($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setSerializedData($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerializedData', [$value]);

        return parent::setSerializedData($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setExportOperationType($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExportOperationType', [$value]);

        return parent::setExportOperationType($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getSerializedData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerializedData', []);

        return parent::getSerializedData();
    }

    /**
     * {@inheritDoc}
     */
    public function getExportOperationType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExportOperationType', []);

        return parent::getExportOperationType();
    }

}
