<?php

namespace Proxies\__CG__\Oro\Bundle\PayPalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PayPalSettings extends \Oro\Bundle\PayPalBundle\Entity\PayPalSettings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'settings', 'creditCardPaymentAction', 'expressCheckoutPaymentAction', 'allowedCreditCardTypes', 'creditCardLabels', 'creditCardShortLabels', 'expressCheckoutLabels', 'expressCheckoutShortLabels', 'expressCheckoutName', 'partner', 'vendor', 'user', 'password', 'testMode', 'debugMode', 'requireCVVEntry', 'zeroAmountAuthorization', 'authorizationForRequiredAmount', 'useProxy', 'proxyHost', 'proxyPort', 'enableSSLVerification', 'id', 'channel'];
        }

        return ['__isInitialized__', 'settings', 'creditCardPaymentAction', 'expressCheckoutPaymentAction', 'allowedCreditCardTypes', 'creditCardLabels', 'creditCardShortLabels', 'expressCheckoutLabels', 'expressCheckoutShortLabels', 'expressCheckoutName', 'partner', 'vendor', 'user', 'password', 'testMode', 'debugMode', 'requireCVVEntry', 'zeroAmountAuthorization', 'authorizationForRequiredAmount', 'useProxy', 'proxyHost', 'proxyPort', 'enableSSLVerification', 'id', 'channel'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PayPalSettings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSettingsBag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettingsBag', []);

        return parent::getSettingsBag();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpressCheckoutName($expressCheckoutName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpressCheckoutName', [$expressCheckoutName]);

        return parent::setExpressCheckoutName($expressCheckoutName);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpressCheckoutName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpressCheckoutName', []);

        return parent::getExpressCheckoutName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartner($partner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartner', [$partner]);

        return parent::setPartner($partner);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartner', []);

        return parent::getPartner();
    }

    /**
     * {@inheritDoc}
     */
    public function setVendor($vendor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVendor', [$vendor]);

        return parent::setVendor($vendor);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendor', []);

        return parent::getVendor();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setTestMode($testMode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTestMode', [$testMode]);

        return parent::setTestMode($testMode);
    }

    /**
     * {@inheritDoc}
     */
    public function getTestMode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTestMode', []);

        return parent::getTestMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setDebugMode($debugMode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDebugMode', [$debugMode]);

        return parent::setDebugMode($debugMode);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebugMode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebugMode', []);

        return parent::getDebugMode();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequireCVVEntry($requireCVVEntry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequireCVVEntry', [$requireCVVEntry]);

        return parent::setRequireCVVEntry($requireCVVEntry);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequireCVVEntry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequireCVVEntry', []);

        return parent::getRequireCVVEntry();
    }

    /**
     * {@inheritDoc}
     */
    public function setZeroAmountAuthorization($zeroAmountAuthorization)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZeroAmountAuthorization', [$zeroAmountAuthorization]);

        return parent::setZeroAmountAuthorization($zeroAmountAuthorization);
    }

    /**
     * {@inheritDoc}
     */
    public function getZeroAmountAuthorization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZeroAmountAuthorization', []);

        return parent::getZeroAmountAuthorization();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorizationForRequiredAmount($authorizationForRequiredAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorizationForRequiredAmount', [$authorizationForRequiredAmount]);

        return parent::setAuthorizationForRequiredAmount($authorizationForRequiredAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorizationForRequiredAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorizationForRequiredAmount', []);

        return parent::getAuthorizationForRequiredAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setUseProxy($useProxy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUseProxy', [$useProxy]);

        return parent::setUseProxy($useProxy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUseProxy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUseProxy', []);

        return parent::getUseProxy();
    }

    /**
     * {@inheritDoc}
     */
    public function setProxyHost($proxyHost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProxyHost', [$proxyHost]);

        return parent::setProxyHost($proxyHost);
    }

    /**
     * {@inheritDoc}
     */
    public function getProxyHost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProxyHost', []);

        return parent::getProxyHost();
    }

    /**
     * {@inheritDoc}
     */
    public function setProxyPort($proxyPort)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProxyPort', [$proxyPort]);

        return parent::setProxyPort($proxyPort);
    }

    /**
     * {@inheritDoc}
     */
    public function getProxyPort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProxyPort', []);

        return parent::getProxyPort();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnableSSLVerification($enableSSLVerification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnableSSLVerification', [$enableSSLVerification]);

        return parent::setEnableSSLVerification($enableSSLVerification);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnableSSLVerification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnableSSLVerification', []);

        return parent::getEnableSSLVerification();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreditCardLabel(\Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue $creditCardLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreditCardLabel', [$creditCardLabel]);

        return parent::addCreditCardLabel($creditCardLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreditCardLabel(\Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue $creditCardLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreditCardLabel', [$creditCardLabel]);

        return parent::removeCreditCardLabel($creditCardLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditCardLabels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditCardLabels', []);

        return parent::getCreditCardLabels();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreditCardShortLabel(\Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue $creditCardShortLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreditCardShortLabel', [$creditCardShortLabel]);

        return parent::addCreditCardShortLabel($creditCardShortLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreditCardShortLabel(\Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue $creditCardShortLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreditCardShortLabel', [$creditCardShortLabel]);

        return parent::removeCreditCardShortLabel($creditCardShortLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditCardShortLabels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditCardShortLabels', []);

        return parent::getCreditCardShortLabels();
    }

    /**
     * {@inheritDoc}
     */
    public function addExpressCheckoutLabel(\Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue $expressCheckoutLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExpressCheckoutLabel', [$expressCheckoutLabel]);

        return parent::addExpressCheckoutLabel($expressCheckoutLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExpressCheckoutLabel(\Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue $expressCheckoutLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExpressCheckoutLabel', [$expressCheckoutLabel]);

        return parent::removeExpressCheckoutLabel($expressCheckoutLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpressCheckoutLabels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpressCheckoutLabels', []);

        return parent::getExpressCheckoutLabels();
    }

    /**
     * {@inheritDoc}
     */
    public function addExpressCheckoutShortLabel(\Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue $expressCheckoutShortLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExpressCheckoutShortLabel', [$expressCheckoutShortLabel]);

        return parent::addExpressCheckoutShortLabel($expressCheckoutShortLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExpressCheckoutShortLabel(\Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue $expressCheckoutShortLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExpressCheckoutShortLabel', [$expressCheckoutShortLabel]);

        return parent::removeExpressCheckoutShortLabel($expressCheckoutShortLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpressCheckoutShortLabels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpressCheckoutShortLabels', []);

        return parent::getExpressCheckoutShortLabels();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowedCreditCardTypes(array $allowedCreditCardTypes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowedCreditCardTypes', [$allowedCreditCardTypes]);

        return parent::setAllowedCreditCardTypes($allowedCreditCardTypes);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllowedCreditCardTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllowedCreditCardTypes', []);

        return parent::getAllowedCreditCardTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditCardPaymentAction($creditCardPaymentAction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditCardPaymentAction', [$creditCardPaymentAction]);

        return parent::setCreditCardPaymentAction($creditCardPaymentAction);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditCardPaymentAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditCardPaymentAction', []);

        return parent::getCreditCardPaymentAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpressCheckoutPaymentAction($expressCheckoutPaymentAction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpressCheckoutPaymentAction', [$expressCheckoutPaymentAction]);

        return parent::setExpressCheckoutPaymentAction($expressCheckoutPaymentAction);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpressCheckoutPaymentAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpressCheckoutPaymentAction', []);

        return parent::getExpressCheckoutPaymentAction();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setChannel(\Oro\Bundle\IntegrationBundle\Entity\Channel $channel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChannel', [$channel]);

        return parent::setChannel($channel);
    }

    /**
     * {@inheritDoc}
     */
    public function getChannel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannel', []);

        return parent::getChannel();
    }

}
